version: '3.8'

services:
  user-service:
    build: ./user_service
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env  # Load environment variables from the .env file

  db:
    build: ./db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      timeout: 5s
    env_file:
      - .env  # Load environment variables from the .env file

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    env_file:
      - .env  # Load environment variables from the .env file

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - user-service
